In [58]:
import sys, string, math
from math import log
from math import modf
import operator

import numpy as np

final = {}
datam={}
topic_array = []
d = 0.85

stop_words = ['ourselves', 'hers', 'between', 'yourself', 'but', 'again', 'there', 'about', 'once', 'during', 'out', 'very', 'having', 'with', 'they', 'own', 'an', 'be', 'some', 'for', 'do', 'its', 'yours', 'such', 'into', 'of', 'most', 'itself', 'other', 'off', 'is', 's', 'am', 'or', 'who', 'as', 'from', 'him', 'each', 'the', 'themselves', 'until', 'below', 'are', 'we', 'these', 'your', 'his', 'through', 'don', 'no', 'me', 'were', 'her', 'more', 'himself', 'this', 'down', 'should', 'our', 'their', 'while', 'above', 'both', 'up', 'to', 'ours', 'had', 'she', 'all', 'no', 'when', 'at', 'any', 'before', 'them', 'same', 'and', 'been', 'have', 'in', 'will', 'on', 'does', 'yourselves', 'then', 'that', 'because', 'what', 'over', 'why', 'so', 'can', 'did', 'not', 'now', 'under', 'he', 'you', 'herself', 'has', 'just', 'where', 'too', 'only', 'myself', 'which', 'those', 'i', 'after', 'few', 'whom', 't', 'being', 'if', 'theirs', 'my', 'against', 'a', 'by', 'doing', 'it', 'how', 'further', 'was', 'here', 'than'] 

for word in open('input_topic.txt', 'r').readline().split():
    topic_array.append(word)

def parse_file():
    #print(datam)
    for word in topic_array:
        for key in datam.keys():
            if key  not in final:
                if word in datam[key]:
                    
                    final[key]= datam[key]
                    final[key].remove(word)

    rows,cols = (len(final),len(final))
    arr = [[0 for i in range(cols)] for j in range(rows)]
   
    final_s= {}
    for x in sorted(final):
        final_s[x] = final[x]

    i =  0
    j  = 0

    for key1 in final_s:
        j = 0
        for key2 in final_s:
            
            arr[i][j] = float(len([value for value in final_s[key1] if value in final_s[key2]]))/float(len(final_s[key2]))
            if j<len(final_s):
                j = j+1
        if i< len(final_s):
            i= i+1
            
    col_sum = list(sum(z) for z in zip(*arr))
    i =  0
    j  = 0
    for key1 in final_s:
        j = 0
        for key2 in final_s:
            
            arr[i][j]= arr[i][j]/float(col_sum[i])
           
            if j<len(final_s):
                j = j+1
        if i< len(final_s):
            i= i+1
    
    arr= np.array(arr)
    
    arr = d*arr
    
    r = [1.0/float(len(final_s)) for i in range(len(final_s))]
    
    r_random = [1.0/float(len(final_s)) for i in range(len(final_s))]
    r_random = np.array(r_random)
    r_random = (1-d)*r_random
    #print(r_random)
    it = 0
    while(it<20):

        r = np.dot(arr,r)
        r= r+r_random
        print(r)

        it = it+1

    
    r = np.array(r)

    
    maximum= np.max(r)
    ans_index= np.argmax(r, axis=0)
    
    
    print("Final Ranks")
    print(r)
    print("Page with highest rank:",ans_index)
    #print(final[ans_index])
#######################################################################
if __name__ == "__main__":

        f = open('article-Copy1.txt', 'r')

        data = f.read()
        splat = data.split("\n\n")
        
        ind = 0
        for para in splat:
            
            datam[ind]=  list(np.setdiff1d([word.lower() for word in para.split()],stop_words))
            if(ind > -1):
                ind= ind+1
            
   
        parse_file()


[0.20227929 0.23494018 0.19494654 0.19044148 0.19044148]
[0.20383428 0.25295256 0.19389591 0.18488643 0.18488643]
[0.20490213 0.2623337  0.19416005 0.18164625 0.18164625]
[0.20562599 0.26727158 0.19472184 0.17975095 0.17975095]
[0.20610756 0.26989885 0.19524031 0.17863991 0.17863991]
[0.20642199 0.2713118  0.19563262 0.17798751 0.17798751]
[0.20662387 0.27207971 0.19590415 0.17760392 0.17760392]
[0.20675164 0.27250125 0.19608298 0.17737816 0.17737816]
[0.20683154 0.27273486 0.19619719 0.17724519 0.17724519]
[0.206881   0.27286544 0.19626864 0.17716682 0.17716682]
[0.20691138 0.27293901 0.19631271 0.17712061 0.17712061]
[0.2069299  0.27298076 0.19633961 0.17709336 0.17709336]
[0.20694113 0.27300459 0.19635591 0.17707728 0.17707728]
[0.20694791 0.27301828 0.19636573 0.17706779 0.17706779]
[0.20695198 0.27302617 0.19637162 0.17706219 0.17706219]
[0.20695443 0.27303074 0.19637515 0.17705888 0.17705888]
[0.20695589 0.27303339 0.19637725 0.17705693 0.17705693]
[0.20695676 0.27303494 0.196378